name: check

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}

permissions:
  contents: read

jobs:
  check:
    if: ${{ ! startsWith(github.event.head_commit.message, 'bump:') }}
    runs-on: ubuntu-24.04
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@0a2f62e3b132c09b144b6957976f538f79fc81a2 # v1.10.0

      - name: Run checks
        run: nix flake check

  compare-devshell:
    name: compare (devshell)
    if: ${{ ! startsWith(github.event.head_commit.message, 'bump:') }}
    runs-on: ubuntu-24.04
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@0a2f62e3b132c09b144b6957976f538f79fc81a2 # v1.10.0
        with:
          shell: check

      - name: Fix hashes in bad.nix
        run: nix-fix-hash --file tests/bad.nix

      - name: Compare bad.nix with good.nix
        run: diff -u tests/good.nix tests/bad.nix

  compare-docker:
    name: compare (docker)
    if: ${{ ! startsWith(github.event.head_commit.message, 'bump:') }}
    runs-on: ubuntu-24.04
    steps:
      - name: Initialize
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Fix hashes in bad.nix
        uses: spotdemo4/nix-fix-hash@9d7e396cd940e50a7ff57d97e4fcc6eeab8b7b19 # v0.1.1
        with:
          arguments: --file tests/bad.nix

      - name: Compare bad.nix with good.nix
        run: diff -u tests/good.nix tests/bad.nix
